# Generated by Django 5.2.4 on 2025-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('utensils', 'Food'), ('car', 'Transportation'), ('home', 'Housing'), ('shopping-cart', 'Shopping'), ('film', 'Entertainment'), ('heart', 'Health'), ('lightbulb', 'Utilities'), ('book', 'Education')], default='receipt', max_length=30, verbose_name='Icon'),
        ),
    ]
